//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace nguoiduado.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class nguoiduado_dbEntities : DbContext
    {
        public nguoiduado_dbEntities()
            : base("name=nguoiduado_dbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<TBL_AD_Menu> TBL_AD_Menu { get; set; }
        public virtual DbSet<TBL_AD_VaiTro> TBL_AD_VaiTro { get; set; }
        public virtual DbSet<TBL_AD_VaiTro_Menu> TBL_AD_VaiTro_Menu { get; set; }
        public virtual DbSet<TBL_AD_VaiTro_NguoiDung> TBL_AD_VaiTro_NguoiDung { get; set; }
        public virtual DbSet<TBL_Counter> TBL_Counter { get; set; }
        public virtual DbSet<TBL_DanhMucNghiaTrang> TBL_DanhMucNghiaTrang { get; set; }
        public virtual DbSet<TBL_DanhSachLietSi> TBL_DanhSachLietSi { get; set; }
        public virtual DbSet<TBL_DiaPhuong> TBL_DiaPhuong { get; set; }
        public virtual DbSet<TBL_LichSu> TBL_LichSu { get; set; }
        public virtual DbSet<TBL_LienKet> TBL_LienKet { get; set; }
        public virtual DbSet<TBL_MenuDanhMuc> TBL_MenuDanhMuc { get; set; }
        public virtual DbSet<TBL_NoiDung> TBL_NoiDung { get; set; }
        public virtual DbSet<TBL_NoiDung_lienQuan> TBL_NoiDung_lienQuan { get; set; }
        public virtual DbSet<TBL_PhanHoi> TBL_PhanHoi { get; set; }
        public virtual DbSet<TBL_Picture> TBL_Picture { get; set; }
        public virtual DbSet<TBL_QuangCao> TBL_QuangCao { get; set; }
        public virtual DbSet<TBL_ThanhVien> TBL_ThanhVien { get; set; }
        public virtual DbSet<TBL_ThuVienAnh> TBL_ThuVienAnh { get; set; }
        public virtual DbSet<TBL_User> TBL_User { get; set; }
        public virtual DbSet<TBL_VanBan> TBL_VanBan { get; set; }
        public virtual DbSet<TBL_Video> TBL_Video { get; set; }
    }
}
