//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace nguoiduado.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_LichSu
    {
        public int IDLichSu { get; set; }
        public string NguoiTao { get; set; }
        public string NguoiCapNhat { get; set; }
        public Nullable<System.DateTime> NgayCapNhat { get; set; }
        public Nullable<decimal> MaNoiDung { get; set; }
        public string TieuDe { get; set; }
        public string Menu { get; set; }
        public string NguonTin { get; set; }
        public string FileAttachment { get; set; }
        public string LoaiKhaiThac { get; set; }
        public string LoaiBaiViet { get; set; }
        public string TrichDan { get; set; }
        public string ChiTiet { get; set; }
        public string Tag { get; set; }
        public string TrangThai { get; set; }
        public Nullable<int> PictureId { get; set; }
        public string PictureBinary { get; set; }
        public string MimeType { get; set; }
    }
}
