//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace nguoiduado.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_NoiDung
    {
        public TBL_NoiDung()
        {
            this.TBL_NoiDung_lienQuan = new HashSet<TBL_NoiDung_lienQuan>();
            this.TBL_PhanHoi = new HashSet<TBL_PhanHoi>();
        }
    
        public decimal MaNoiDung { get; set; }
        public string MaSo { get; set; }
        public Nullable<decimal> MenuID { get; set; }
        public string TieuDe { get; set; }
        public string LinkAnh { get; set; }
        public string NoiDung { get; set; }
        public string TrichDan { get; set; }
        public string Comment { get; set; }
        public string NguoiNhap { get; set; }
        public Nullable<System.DateTime> NgayNhap { get; set; }
        public string NguoiCapNhat { get; set; }
        public Nullable<System.DateTime> NgayCapNhat { get; set; }
        public Nullable<int> TrangThaiPhatHanh { get; set; }
        public Nullable<int> MucUuTienBaiViet { get; set; }
        public string NguonTin { get; set; }
        public string NguoiDuyet { get; set; }
        public Nullable<System.DateTime> NgayDuyet { get; set; }
        public Nullable<int> LuotXem { get; set; }
        public string FileWord { get; set; }
        public int PictureId { get; set; }
        public string FileImage { get; set; }
        public string KhaiThac { get; set; }
        public string MaLienQuanBaiViet { get; set; }
        public string Tag { get; set; }
        public string TuKhoaTag { get; set; }
        public Nullable<int> TrangThaiSua { get; set; }
        public bool ExistVideo { get; set; }
    
        public virtual TBL_MenuDanhMuc TBL_MenuDanhMuc { get; set; }
        public virtual ICollection<TBL_NoiDung_lienQuan> TBL_NoiDung_lienQuan { get; set; }
        public virtual ICollection<TBL_PhanHoi> TBL_PhanHoi { get; set; }
    }
}
