//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace nguoiduado.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_DanhMucNghiaTrang
    {
        public int ID { get; set; }
        public Nullable<decimal> MaDiaPhuong { get; set; }
        public string TenNghiaTrang { get; set; }
        public string NoiDungMoTa { get; set; }
        public int PictureId { get; set; }
    }
}
