//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace nguoiduado.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_AD_VaiTro
    {
        public TBL_AD_VaiTro()
        {
            this.TBL_AD_VaiTro_Menu = new HashSet<TBL_AD_VaiTro_Menu>();
            this.TBL_AD_VaiTro_NguoiDung = new HashSet<TBL_AD_VaiTro_NguoiDung>();
            this.TBL_User = new HashSet<TBL_User>();
        }
    
        public decimal MaVaiTro { get; set; }
        public string TenVaiTro { get; set; }
        public string GhiChu { get; set; }
        public Nullable<System.DateTime> NgayTao { get; set; }
        public string NguoiTao { get; set; }
        public Nullable<System.DateTime> NgayCapNhat { get; set; }
        public string NguoiCapNhat { get; set; }
        public bool PhatHanhBaiViet { get; set; }
    
        public virtual ICollection<TBL_AD_VaiTro_Menu> TBL_AD_VaiTro_Menu { get; set; }
        public virtual ICollection<TBL_AD_VaiTro_NguoiDung> TBL_AD_VaiTro_NguoiDung { get; set; }
        public virtual ICollection<TBL_User> TBL_User { get; set; }
    }
}
