//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace nguoiduado.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_VanBan
    {
        public int ID { get; set; }
        public string TenVanBan { get; set; }
        public string CoQuanPhatHanh { get; set; }
        public string SoHieu { get; set; }
        public Nullable<System.DateTime> NgayBanHanh { get; set; }
        public string TrichYeuNoiDung { get; set; }
        public string NguoiKy { get; set; }
        public string LoaiVanBan { get; set; }
        public string TepVanBan1 { get; set; }
        public string TepVanBan2 { get; set; }
        public string TepVanBan3 { get; set; }
        public string TepVanBan4 { get; set; }
        public string TepVanBan5 { get; set; }
        public Nullable<System.DateTime> NgayTao { get; set; }
        public string NguoiTao { get; set; }
        public Nullable<System.DateTime> NgayCapNhat { get; set; }
        public string NguoiCapNhat { get; set; }
    }
}
