//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace nguoiduado.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_MenuDanhMuc
    {
        public TBL_MenuDanhMuc()
        {
            this.TBL_NoiDung = new HashSet<TBL_NoiDung>();
        }
    
        public decimal MenuID { get; set; }
        public Nullable<int> CapMenu { get; set; }
        public Nullable<int> MenuCha { get; set; }
        public string TenMenu { get; set; }
        public string Link { get; set; }
        public Nullable<int> ThuTu { get; set; }
        public Nullable<bool> TrangThaiHienThi { get; set; }
    
        public virtual ICollection<TBL_NoiDung> TBL_NoiDung { get; set; }
    }
}
