//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace nguoiduado.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_PhanHoi
    {
        public int ID { get; set; }
        public Nullable<decimal> MaNoiDung { get; set; }
        public string Noidung { get; set; }
        public Nullable<bool> TrangThai { get; set; }
        public System.DateTime NgayDangTin { get; set; }
        public string TenNguoiDang { get; set; }
        public string SoDienThoai { get; set; }
        public string Email { get; set; }
        public Nullable<decimal> MaUser { get; set; }
        public int MaPhanHoiCha { get; set; }
    
        public virtual TBL_NoiDung TBL_NoiDung { get; set; }
    }
}
