//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace nguoiduado.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_AD_Menu
    {
        public TBL_AD_Menu()
        {
            this.TBL_AD_VaiTro_Menu = new HashSet<TBL_AD_VaiTro_Menu>();
        }
    
        public decimal MaMenu { get; set; }
        public Nullable<byte> CapMenu { get; set; }
        public Nullable<decimal> MaMenuCha { get; set; }
        public string ControllerName { get; set; }
        public string TenMenu { get; set; }
        public Nullable<System.DateTime> NgayTao { get; set; }
        public string NguoiTao { get; set; }
        public Nullable<System.DateTime> NgayCapNhat { get; set; }
        public string NguoiCapNhat { get; set; }
        public Nullable<bool> SuDung { get; set; }
    
        public virtual ICollection<TBL_AD_VaiTro_Menu> TBL_AD_VaiTro_Menu { get; set; }
    }
}
