//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace nguoiduado.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_DanhSachLietSi
    {
        public int LietSiID { get; set; }
        public string HoVaTen { get; set; }
        public string NamSinh { get; set; }
        public string NguyenQuan { get; set; }
        public string CapBacChucVu { get; set; }
        public string DonViLucHySinh { get; set; }
        public Nullable<System.DateTime> NgayHiSinh { get; set; }
        public string HoVaTenThanNhan { get; set; }
        public string DiaChiThanNhan { get; set; }
        public string DienThoaiThanNhan { get; set; }
        public string EmailThanNhan { get; set; }
        public string MoTaThem { get; set; }
        public bool TrangThaiHienThi { get; set; }
    }
}
